### ISSUE TITLE
S3 activity

### ISSUE THREAD

**Issue by snehal-herovired** [snehal-herovired/Devops_Batch_Aditya#48]

**Comment by 20A91A04G7** [comment]
https://firstbucket1234.s3.amazonaws.com/SAMPLE.docx

**Comment by 20A91A04L7** [comment]
https://mypractisebucket121.s3.amazonaws.com/hero.txt

**Comment by NandaKishore777** [comment]
20A91A0442--KISHORE
https://mybuc12.s3.ap-northeast-1.amazonaws.com/NANDA+KISHORE+(3).pdf
http://mybuc12.s3-website-ap-northeast-1.amazonaws.com

**Comment by kalpanamaddipatla** [comment]
https://kalpanachawla.s3.amazonaws.com/vpc+peer.pdf

#20A91A04F3

**Comment by 20a91a04e1** [comment]
https://bucket0619.s3.amazonaws.com/link+of+grand+assessment.txt

G.Bhavana
20A91A04E1

**Comment by priya312003** [comment]
https://mybuckethub.s3.amazonaws.com/sample.docx


20A91A04G0
N.PRIYANKA

**Comment by 20A91A04D1** [comment]
https://mmmmmm111.s3.amazonaws.com/docker.txt

20A91A04D1
Bh.Gayathri

**Comment by Naveenindukuri** [comment]
https://naveen-bucket11.s3.amazonaws.com/Screenshot+(169).png

20A91A2708
I.NAVEEN

**Comment by 20A91A04D3** [comment]
https://harshasrivalli.s3.amazonaws.com/task.pdf

20A91A04D3
B.Harsha Srivalli

**Comment by saikrishna5555** [comment]
http://hostingpractice.s3-website.ap-south-1.amazonaws.com
20MH1A04B5
P.SAI KRISHNA

**Comment by sravya-nanduri** [comment]
http://sravya111.s3-website-us-east-1.amazonaws.com
20A91A04I1
Sravya N

**Comment by kamisetti-kavya-12345** [comment]
http://kavya543.s3-website-us-east-1.amazonaws.com

20a91a04e5
kavya

**Comment by 20A91A04L4** [comment]
https://akash888.s3.amazonaws.com/awsNotes.txt
https://akash888.s3.amazonaws.com/Amazon+static+webpage/index.html

20A91A04L4
K.N.P.R.AKASH

**Comment by gokarakondaswamy** [comment]
https://swamybuck.s3.amazonaws.com/2022-11-03.png
https://htmlbuck123.s3.amazonaws.com/index.html
21mh5a0363
swamy

**Comment by Sandhya-Akula** [comment]
https://aws402-2.s3.amazonaws.com/numbers.py
http://aws402.s3-website-us-east-1.amazonaws.com
 20A91A0402
A.Sandhya

**Comment by shashank763** [comment]
https://s3bucketqwwer.s3.amazonaws.com/s3bucket.txt
http://s33udasfhufnao.s3-website-us-east-1.amazonaws.com/
20A91A04A1
Shashank

**Comment by Bhavani-maddukuri** [comment]
http://bhavanabhavana.s3-website-us-east-1.amazonaws.com
https://bhavanabhavana.s3.amazonaws.com/index.html

20A91A0487
M.Bhavani

**Comment by Deepika-Gutti** [comment]
http://deepika-bucket1.s3-website-us-east-1.amazonaws.com
https://deepika-bucket1.s3.amazonaws.com/python+certification.pdf
20A91A0413
G.Deepika

**Comment by devaraharsha** [comment]
https://harshabro.s3.amazonaws.com/history.png
https://harshabro12.s3.amazonaws.com/index.html
20P31A04J4

**Comment by 20A91A04P0** [comment]
https://shanmukh033.s3.ap-south-1.amazonaws.com/Amazon+static+webpage/index.html

https://shanmukh033.s3.ap-south-1.amazonaws.com/EC-2+INSTANCE+ASSIGNMENT.pdf

20A91A04P0

**Comment by Vinaybogilli** [comment]
https://mybucket8380.s3.amazonaws.com/index.html
https://mybucket7385.s3.amazonaws.com/BOGILLISAI+VINAY-Becomecoder2022_-certificate+(1).pdf
20P31A04J1

**Comment by Abhinand-ECE** [comment]
http://toppermani.s3-website-us-east-1.amazonaws.com

20A91A0440
P.Abhinand

**Comment by 21A95A0418** [comment]
http://mysamplebucket12341589.s3-website-us-east-1.amazonaws.com

21A95A0418
G.satyanarayana

**Comment by 21a95a0420** [comment]
http://cloudko3.s3-website-ap-northeast-1.amazonaws.com

21a95a0420
m.komal

**Comment by 20A91A0435** [comment]
http://mybucket435.s3-website-us-east-1.amazonaws.com
20A91A0435
manikanta

**Comment by Yaswanth4991** [comment]
https://assiignment.s3.amazonaws.com/ASSIGNMENT.txt

**Comment by bsrtej** [comment]
http://staticwebsiteeeee.s3-website-us-east-1.amazonaws.com
21a95a0427
teja

**Comment by Gangadhar-7** [comment]
http://gangkishore.s3-website-us-east-1.amazonaws.com

#21MH5A0416

**Comment by pavithrakuricheti534** [comment]
Static Web Hosting : http://mypavithrabuck01.s3-website-us-east-1.amazonaws.com/
Object links: https://mypavithrabuck01.s3.amazonaws.com/amazon.png
https://mypavithrabuck01.s3.amazonaws.com/index.html
https://mypavithrabuck01.s3.amazonaws.com/index.js
https://mypavithrabuck01.s3.amazonaws.com/style.css

**Comment by pavithrakuricheti534** [comment]
Static Web Hosting : http://mypavithrabuck01.s3-website-us-east-1.amazonaws.com/
Object links: https://mypavithrabuck01.s3.amazonaws.com/amazon.png
https://mypavithrabuck01.s3.amazonaws.com/index.html
https://mypavithrabuck01.s3.amazonaws.com/index.js

https://mypavithrabuck01.s3.amazonaws.com/style.css
//20A91A0485

**Comment by Mahesh-1919** [comment]
object url -- https://bucket437.s3.amazonaws.com/task.docx
static website -- https://webhost437.s3.amazonaws.com/index.html
21MH5A0437

**Comment by 20A91A04D9** [comment]
https://mybuck06.s3.amazonaws.com/s3.txt

20A91A04D9
G.NagaTrinath

**Comment by Nikhil7650** [comment]
object url : https://ni11.s3.amazonaws.com/nikhil.txt
static website : http://nikh1.s3-website-us-east-1.amazonaws.com

20A91A0491
M.NIKHIL

**Comment by Yaswanth4991** [comment]
http://webhosting12345.s3-website-us-east-1.amazonaws.com/

STATIC WEB HOSTING

21A95A0419

**Comment by likithaanusha** [comment]
static website :
http://geethabhavani.s3-website-us-east-1.amazonaws.com
object URL :
https://geethabhavani.s3.amazonaws.com/amazon.png
https://geethabhavani.s3.amazonaws.com/index.html
https://geethabhavani.s3.amazonaws.com/index.js
https://geethabhavani.s3.amazonaws.com/style.css
Name: J Geethabhavani
Roll : 20A91A04K5

**Comment by sidda-chitti** [comment]
http://chitti123.s3-website-us-east-1.amazonaws.com
https://chitti123.s3.amazonaws.com/index.html

20A91A0449
S.CHITTI

**Comment by 21a95a0423** [comment]
http://ram423.s3-website-us-east-1.amazonaws.com
21a95a0423
A.RAMBABU

**Comment by mounika-gtb** [comment]
static website: 
http://mounika89786.s3-website-us-east-1.amazonaws.com/
object URL:
https://mounika89786.s3.amazonaws.com/amazon.png

20A91A0472
Ch.Mounika

**Comment by Mani10101** [comment]
http://squider.s3-website-us-east-1.amazonaws.com
21A95A0358

**Comment by 20A91A2715** [comment]
20A91A2715
Madhavi Manohari Palaparthi
Object Url : https://madhavipalaparthi12.s3.amazonaws.com/abc.txt
Static Website : http://madhavipalaparthi12.s3-website-us-east-1.amazonaws.com

**Comment by Kumar1199** [comment]
20A91A0345
MANIKANTA KUMAR
WEBSITE URL:http://staticwebsitetask.s3-website-us-east-1.amazonaws.com/
https://s3testtoday.s3.amazonaws.com/gcp+nasscom.pdf

**Comment by Anusha-286** [comment]
20A91A04K9
Jyothi Lakshmi Anusha Yaramalla
Object Url : 
https://awsbucket1628.s3.amazonaws.com/amazon.png
https://awsbucket1628.s3.amazonaws.com/index.html
https://awsbucket1628.s3.amazonaws.com/index.js
https://awsbucket1628.s3.amazonaws.com/style.css
Static Website : 
http://awsbucket1628.s3-website-us-east-1.amazonaws.com

**Comment by 20A91A04L7** [comment]
20A91A04L7
Static webhosting: https://mypractisebucket121.s3.amazonaws.com/index.html
https://mypractisebucket121.s3.amazonaws.com/hero.txt

**Comment by AEC-ECE-D** [comment]
object: https://mybucket4l8.s3.amazonaws.com/herovied.txt
static: http://mybucket4l8.s3-website-us-east-1.amazonaws.com
20a91a04l8

**Comment by prasannachowdary12** [comment]
http://chowdary12.s3-website-us-east-1.amazonaws.com
https://chowdary12.s3.amazonaws.com/amazon.png

M. Durga prasanna
20A91A0429

**Comment by RobinvargheseO4** [comment]
https://mybucrob234.s3.amazonaws.com/Assignment_robin.pdf
http://mybucrob54.s3-website-us-east-1.amazonaws.com
Robin Varghese
20A91A04O4

**Comment by 20A91A04J3** [comment]
http://thub1.s3-website-us-east-1.amazonaws.com
https://thub1.s3.amazonaws.com/amazon.png
20A91A04J3
suryakanthi
